"""Add parent_comment_id and reply_count to comments

Revision ID: 8c40e2d36e87
Revises: c775ebd68aac
Create Date: 2025-11-17 14:25:27.113734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c40e2d36e87'
down_revision: Union[str, None] = 'c775ebd68aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.UUID(), nullable=True))
    op.add_column('comments', sa.Column('reply_count', sa.Integer(), nullable=False, server_default='0'))
    # Remove server_default after adding the column
    op.alter_column('comments', 'reply_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_count')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
