"""add track upload and processing fields

Revision ID: c775ebd68aac
Revises: 3af0db1955dd
Create Date: 2025-11-17 11:21:12.688220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c775ebd68aac'
down_revision: Union[str, None] = '3af0db1955dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first
    trackprocessingstatus = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='trackprocessingstatus')
    trackprocessingstatus.create(op.get_bind(), checkfirst=True)

    op.add_column('tracks', sa.Column('original_audio_url', sa.String(length=2048), nullable=True))
    op.add_column('tracks', sa.Column('processing_status', trackprocessingstatus, nullable=False, server_default='PENDING'))
    op.add_column('tracks', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'duration_seconds')
    op.drop_column('tracks', 'processing_error')
    op.drop_column('tracks', 'processing_status')
    op.drop_column('tracks', 'original_audio_url')

    # Drop ENUM type
    trackprocessingstatus = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='trackprocessingstatus')
    trackprocessingstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
